version: "3"

services:

  serving:
    build:
      context: serving
      dockerfile: docker/Dockerfile.amd64
    image: serving

  api:
    image: serving
    depends_on:
      - serving
    environment:
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=entrypoints/app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"
