version: "3"

services:

  serving:
    build:
      context: serving
      dockerfile: docker/Dockerfile.amd64
    image: serving

  api:
    image: serving
    environment:
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=entrypoints/app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    ports:
      - "5000:5000"
