version: "3"

services:

  serving:
    build:
      context: modules/serving
      dockerfile: docker/Dockerfile.amd64
    image: iotserving

  api:
    image: iotserving
    depends_on:
      - serving
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=entrypoints/app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"

  client:
    build:
      context: modules/client
      dockerfile: docker/Dockerfile.amd64
    volumes:
      - ./modules/tests:/app/tests
    environment:
      - API_HOST=api
    image: iotclient
