FROM nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py3

WORKDIR /app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY requirements-dev.txt .
RUN pip3 install -r requirements-dev.txt

COPY . .
RUN pip3 install -e .
